### PR TITLE
Prevent invalid redirects after logging in. Fix #716

### LINKED ISSUE #716: Only internal redirects
The platform should only redirect to internal pages after logging in.

(handled in `evaluation/views.py index`)

### PR DESCRIPTION
**Pull request by simonkrogmann**
e. g. previously `http://localhost:8000/?next=/http://google.com/` would redirect to google after logging in.

### CODE REVIEW

**Comment by janno42** [comment]
unfortunately this doesn't help

**Comment by simonkrogmann** [comment]
Now it should also handle `http://localhost:8000/?next=http://google.com/` correctly.

**Comment by janno42** [comment]
looks good, thanks :)
if you rebase on the current master the tests shouldn't fail anymore.

**Comment by karyon** [comment]
thanks!

**Pull request merged**
