### PR TITLE
Fix missing messages import, fixes #825

### LINKED ISSUE #825: Missing import for messages
in `evaluation/models.py` the import `from django.contrib import messages` is missing, resulting in an error when `__send_to_user` tries to send a message to a user without email address.

### PR DESCRIPTION
**Pull request by karyon**
fixes #825

### CODE REVIEW

**Comment by janno42** [comment]
do you want to add more landscape issue fixes to this pr?

**Comment by karyon** [comment]
yes.

**Comment by janno42** [comment]
:honey_pot:

**Comment by karyon** [comment]
this wasn't finished, the request parameter was missing. i added that now, please review again.

**Comment by janno42** [comment]
oh right. but looks good!

**Pull request merged**
