### PR TITLE
[WIP] Some cleanup of the html code

### PR DESCRIPTION
**Pull request by lmm-git**
Some corrections to produce valid HTML5 code and some CSS corrections (#489).

Tasks to do:
- [ ] Check student form for valid functionality due to some field-id changes - for this I need the fix of the JavaScript functions on this page; is there already an issue open?
- [x] the function ```{{ form.as_div }}``` in evap/contributor/templates/contributor_course_form.html produces invalid ids (same at some other forms like /staff/semester/XX/edit...)
- [x] the function ```{{ form.as_div }}``` in evap/contributor/templates/contributor_course_form.html produces invalid table-form mixes
- [x] Check all student html files (or frontend functions)
- [x] Check all contributor html files (or frontend functions)
- [x] Check all evaluation html files (or frontend functions)
- [x] Check all results html files (or frontend functions)
- [ ] Check all rewards html files (or frontend functions)
- [ ] Check html files located in templates

### CODE REVIEW

**Comment by karyon** [comment]
fyi, there is a list of all urls we have (here)[https://github.com/fsr-itse/EvaP/blob/8efcb706fa7a4efed4629a9957fe452f0e5c1908/evap/staff/tests.py#L254] and the get_assert_200 in (here)[https://github.com/fsr-itse/EvaP/blob/8efcb706fa7a4efed4629a9957fe452f0e5c1908/evap/staff/tests.py#L360] returns the html code of each of those.

**Comment by lmm-git** [comment]
thanks for this hint!

**Comment by karyon** [comment]
as you removed some occurrences of True/False in html code: django 1.8 will render these by default (see [django 1.8 release notes](http://django.readthedocs.org/en/latest/releases/1.8.html#forms)). so maybe this replacement is not necessary? i'm not sure really.

also, this needs a rebase (try to do that and if you don't manage, do a merge instead). maybe wait for that until #505 is merged.

**Comment by karyon** [comment]
hey @lmm-git, do you want to finish this? otherwise we'd probably rebase and squash the commits and merge the PR in the next couple days/weeks.

**Comment by lmm-git** [comment]
Yes I will work on it in a few days, so its still work in progress ;)
Am 28.02.2015 um 13:15 schrieb karyon:

**Comment by karyon** [comment]
updated version in #611. feel free to continue on this anytime :)

**Pull request closed without merging**
