### PR TITLE
Fix 775

### LINKED ISSUE #775: Swapping contributors in course edit form fails
When you exchange two contributors in the course edit form, it says "a contribution with this contributor already exists"

you can also e.g. replace contributor A by someone who is not yet a contributor, and then replace contributor B by contributor A.

reordering the contribution works, the problem occurs when changing the contributors of the contributions.

### PR DESCRIPTION
**Pull request by karyon**
fix #775 

plus one unrelated commit.

### CODE REVIEW

**Comment by janno42** [comment]
same test as before:
```
KeyError at /staff/semester/21/course/1634/edit
'id'
Exception Location:	/vagrant/evap/staff/forms.py in handle_moved_contributors, line 359
```

**Comment by karyon** [comment]
fixed

**Comment by janno42** [comment]
- have a course with one contributor A
- save
- add contributor A again, change the first A to B
- save, fails
```
DoesNotExist at /staff/semester/21/course/1634/edit
Contribution matching query does not exist.
Exception Location:	/usr/local/lib/python3.4/dist-packages/django/db/models/query.py in get, line 387
```

**Comment by karyon** [comment]
i fixed the crash, but then i got a "regular" form error "contribution already exists". i gave up on that, i couldn't find a fix for it. i marked the corresponding test with @skip.

all four tests are failing without the new workaround, and with it, only three of them fail. so that's something... but it's still a lot of code for a relatively minor issue...

**Comment by karyon** [comment]
one more try. this is so low level that it just has to catch all the edge cases.

**Comment by janno42** [comment]
- have a course with contributor A
- save
- change first contributor to B and add A again
- save -> `Contribution with this Course and Contributor already exists.`

**Comment by karyon** [comment]
i really enjoy learning from my mistakes

**Comment by janno42** [comment]
:tada:

**Pull request merged**
