### PR TITLE
Introduce Select2

### LINKED ISSUE #346: Search field for contributor selection
The current contributor selection is a simple dropdown list with all users. Therefore you can only search for people when starting to type their first name.
This should be changed so that the dropdown is replaced by an edit field that has a dropdown option which can be manually triggered and that opens automatically when starting to type and which then only holds names that contain the typed substring (like the multiselect input alread does).

### PR DESCRIPTION
**Pull request by karyon**
this PR replaces the multiselect plugin with select2, and uses that to fix #346. thanks to @PFischbeck for starting #529.

notes:
 * there is one UI issue left, see screenshot. @janno42, could you have a look at this?
 * there is a small delay when the contributor list opens. here it is acceptable, but on production with more users and for people with slower machines it might be worse.
 * i removed .map and non-minified js files. while they are cool to have we never needed them and i'd rather solve this with a proper asset pipeline.
 * afaik we use jqueryui only for the datepicker now. i considered downloading a custom jqueryui with only the datepicker or replacing it with a bootstrap plugin, but thought it wasn't important enough.

### CODE REVIEW

**Comment by janno42** [comment]
when adding a new contributor to the course the select element does nothing when clicking on it

**Comment by karyon** [comment]
should be finished now. @janno42 i changed your commits so please review these as well.

12 hours ago select2 4.0 final came out, that's included as well.

**Comment by janno42** [comment]
Travis failed...

**Comment by janno42** [comment]
After the tests are fixed, you can :ship: it!

**Pull request merged**
