### PR TITLE
Add is_student method to improve page forwarding

### LINKED ISSUE #629: Page forwarding
When a publishing notice about a course is sent to a participating student who also is a contributor in another course, the link for this student is always redirecting to `.../contributor`. When the student is a staff member, EvaP always opens at `.../staff`.

Mostly students will be using the `.../student` page, so they should always be forwarded to this page, even if they contribute to any courses. Staff users should still be forwarded to `.../staff`, even if they are students.

### PR DESCRIPTION
**Pull request by drs-m**
Implemented 'is_student' method in UserProfile model to check if any students enrollment semester is newer than a possible contribution semester.

fixes #629

### CODE REVIEW

**Comment by karyon** [comment]
code looks good, but i'd really like to have tests for this :)

**Comment by karyon** [comment]
fyi i found out there is also .latest() and earliest() on querysets, see https://docs.djangoproject.com/en/1.8/ref/models/querysets/#latest. but this would require us to deal with exceptions instead of checking for None and wouldn't be worth it, i think.

**Comment by karyon** [comment]
hey @drs-m, any chance you might add tests in the foreseeable future? otherwise i guess i'll do them.

**Comment by drs-m** [comment]
probably not, because I don't know anything about writing test.Am 08. Februar 2016 um 20:11 schrieb karyon <notifications@github.com>:hey @drs-m, any chance you might add tests in the foreseeable future? otherwise i guess i'll do them.—Reply to this email directly or view it on GitHub.

**Comment by karyon** [comment]
superseded by #742, thanks!

**Pull request closed without merging**
