### PR TITLE
Django18 prep

### PR DESCRIPTION
**Pull request by karyon**
some cleanups and django 1.8 preparations to prevent them from bitrotting.

the actual update needs to wait as there is a bug (https://code.djangoproject.com/ticket/24513) that makes tests fail randomly, which is fixed in 1.8.1.

5985864 speeds up the tests, from 42s to 32s here.

### CODE REVIEW

**Comment by janno42** [comment]
5a002640 is great!

**Comment by karyon** [comment]
because evaluation didn't have a urls.py and i didn't bother to change that.

**Comment by janno42** [comment]
:+1:

**Comment by karyon** [comment]
added a urls.py for the evaluation app, :ship:?

**Comment by janno42** [comment]
:shipit:

**Pull request merged**
