### PR TITLE
Django20

### LINKED ISSUE #1035: Update to Django 2.0
Django 2.0 was released: https://docs.djangoproject.com/en/dev/releases/2.0/

* [x] run the tests and see what happens
* [x] run the tests with warnings enabled (-Wall?) and check for deprecations
* [x] (maybe re-export test_data so later diffs are cleaner)
* [x] https://docs.djangoproject.com/en/dev/releases/2.0/#simplified-url-routing-syntax, we could update to that
* [x] https://docs.djangoproject.com/en/dev/releases/2.0/#abstractuser-last-name-max-length-increased-to-150, we need to create that migration
* [x] Subclasses of AbstractBaseUser are no longer required to implement get_short_name() and get_full_name(), we can remove those

And: "A model instance’s primary key now appears in the default Model.\_\_str__() method, e.g. Question object (1)" :)

### PR DESCRIPTION
**Pull request by karyon**
fixes #1035 

some tests are disabled because of https://github.com/vandersonmota/model_mommy/issues/344. i suggest we wait a while and if that takes too long, merge anyway. or maybe workaround it.

### CODE REVIEW

**Comment by janno42** [comment]
I just found that the course preview is broken after applying the changes.

preview

**Comment by karyon** [comment]
removed the files. unfortunately i cannot reproduce the broken course preview, both on windows and the vagrant vm...

**Comment by karyon** [comment]
fixed the broken preview as well. now we just wait for model_mommy to be fixed, don't know whether i'll do that myself anytime soon...

**Comment by karyon** [comment]
i'm gonna merge this now. i [have fixed model_mommy](https://github.com/vandersonmota/model_mommy/pull/355) but received no reply for two weeks, our requirements now specify my fork until that is merged. a `pip3 install --user --upgrade -r requirements.txt` will be required, note the `--upgrade`.

**Pull request merged**
