### PR TITLE
Fix scrolling with a dragged item (#1078)

### PR DESCRIPTION
**Pull request by felixrindt**

### CODE REVIEW

**Comment by karyon** [comment]
in this demo here: http://jsbin.com/tutuzeh/edit?html,js,output it works as expected, and it should be the same scenario as we have. do you want to investigate? please say if you don't, we might just merge anyways or i'll look into it.

**Comment by janno42** [comment]
@karyon on the page you mentioned the same problem exists: if you add more content on top of the table and then drag an item up so far that the table is not visible anymore you also can't stop scrolling.

**Comment by karyon** [comment]
yeah, weird. i actually added a second list and experimented a bit and couldn' reproduce it, but now i can. i'll leave the decision on what to do to you.

**Comment by felixrindt** [comment]
I was also able to reproduce it pretty easily. I'd guess that's it's a bug within sortable.js then.

Anyway, as the corresponding issue is considered FSR major, this would at least make scrolling possible again.

**Comment by felixrindt** [comment]
:tada:

**Pull request merged**
