### PR TITLE
Add Form to send Feedback/Questions from anywhere on the site

### PR DESCRIPTION
**Pull request by schumannd**
Implements #170 

A lot still open to debate, such as:
- General Design of: Button, Form, view_feedback view
- Feedback for successful message. (currently: changes feedback button text...)
- Location of Link to View Feedback Page
- Auto send mail function

### CODE REVIEW

**Comment by schumannd** [comment]
Currently blocked by issue #754

**Comment by janno42** [comment]
see https://github.com/janno42/EvaP/commit/323f776c010b64a78487c639dba9593892fa4d87 for proposed changes to layout and functionality (save current user instead of email field and allow only logged in users to use the feedback form).

we do need some additional features as well:
- we need to save a time stamp for each entry
- staff users must be able to:
  - delete feedback entries
  - mark feedback entries as done
  - sort the table by timestamp, user, marked or not (we can use a datatable like for the results)

**Comment by janno42** [comment]
alternatively we could just send an email to the admins when the feedback form is submitted, which includes the username and the message. that would be way easier and we don't need to store anything in the database.

**Comment by schumannd** [comment]
The points you listed should be easy to implement. So it is simply a matter of preference.

**Comment by schumannd** [comment]
Implemented all features except for ordering of the table. Is this essential?

**Comment by janno42** [comment]
yes, but it should be very easy, you just need to apply a datatable to the table element.

by the way: we need to send an email to the feedback address (not the admins) anyway, so that they know there is a new entry. i still didn't make up my mind whether we should only have the email - @karyon would most certainly tell us that this feature here is not necessary.

**Comment by schumannd** [comment]
I developed this to support future implementation of #212. Is that issue not wanted then anymore? Should #212 also be implemented with an email only, not an extra model?

**Comment by karyon** [comment]
indeed i'd just send an email with the feedback to some address and be done with it. having feedback organization functions inside evap sounds like overkill and feature creep to me. emails have a time stamp, can be deleted, marked as read, and sorted. the only difference is that they won't survive if the staff people change, but if that's so important, maybe you can get an email account from the admins or something.

**Pull request closed without merging**
