### PR TITLE
Refactor QuestionnaireMultipleChoiceField handling of additional description text

### PR DESCRIPTION
**Pull request by Steditor**
Contributes to #788

### CODE REVIEW

**Comment by karyon** [comment]
hey, will you be there on monday? if not, could you rebase this?

**Comment by Steditor** [comment]
I'm not yet sure, whether I'll be there - but I've just rebased anyway.

**Comment by karyon** [comment]
do you remember why we can't render this by ourselves in the template?

**Comment by karyon** [comment]
i have something in the pipeline which kinda makes this obsolete, i now render the widget manually in the templates. but, as overwriting some widget renderers by now actually seems like the technically cleaner solution to me, i'll merge this first, it might be a starting point for more investigation... somewhen... in a few years...

**Comment by karyon** [comment]
thanks!

**Pull request merged**
