### PR TITLE
Make update_courses set last_modified_user to the new cronjob user

### LINKED ISSUE #819: Update "Last modified by" in cronjob
When the cronjob changes a course's state, the field `Last modified` is updated with the respective time, but the field `Last modified by` is not changed. This field should then be empty.

### PR DESCRIPTION
**Pull request by karyon**
Fixes #819

### CODE REVIEW

**Comment by karyon** [comment]
fixed the test failure.

**Comment by janno42** [comment]
maybe you could remove the cronjob user from all user lists? especially in the contributor selection form that would be nice. but it could also be removed in the staff user list.

**Comment by karyon** [comment]
added the custom manager.
```
>>> UserProfile.objects.filter(username="cronjob")
[]
>>> UserProfile.objects.with_cronjob_user().filter(username="cronjob")
[<UserProfile: cronjob>]
```

**Comment by janno42** [comment]
:v:

**Pull request merged**
